In [1]:
import numpy as np

In [2]:
a=[1,2,3,4] #list in python
ar=np.array([1,2,3,4]) #array in python
print(a)

[1, 2, 3, 4]


In [3]:
print(type(a))

<class 'list'>


In [4]:
print(type(ar))

<class 'numpy.ndarray'>


In [5]:
ar.shape #dimensions of the array

(4,)

In [6]:
arr=np.array([[1,2,3,4],[5,6,7,8]]) #2-dimensional array
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr.shape

(2, 4)

In [8]:
arr.T #transpose of matrix

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [9]:
np.dot(arr, arr.T) #dot product of two arrays

array([[ 30,  70],
       [ 70, 174]])

In [10]:
np.random.randint(60,100,10) #displays 10 random numbers between 60 to 100

array([69, 82, 80, 85, 98, 94, 96, 68, 63, 79])

In [11]:
np.random.randint(60,100,(5,5)) #displays a random matrix of shape 2X2 between 60 to 100

array([[94, 65, 84, 74, 61],
       [72, 98, 88, 62, 96],
       [83, 84, 95, 76, 99],
       [83, 65, 76, 76, 71],
       [90, 62, 78, 79, 85]])

In [12]:
matrix = np.random.randint(1,10,(5,5))

In [13]:
print(matrix)

[[4 3 6 3 9]
 [7 3 6 9 4]
 [3 6 3 8 3]
 [4 8 7 7 4]
 [4 3 7 2 7]]


In [14]:
np.min(matrix)

2

In [15]:
np.max(matrix)

9

In [16]:
b=np.random.randint(0,9,8)
print(b)

[8 8 4 8 1 1 0 7]


In [17]:
b.argmin() #returns the index of the minimum element

6

In [18]:
np.unique(b) #unique elements in the matrix

array([0, 1, 4, 7, 8])

In [20]:
x=np.unique(b,return_counts=True) #returns the count of the number of elements
print(x)

(array([0, 1, 4, 7, 8]), array([1, 2, 1, 1, 3]))


In [21]:
#code to print the element with the highest frequency
idx = np.argmax(x[1])
element = x[0][idx]
print(element)

8


In [22]:
#slicing of arrays
matrix

array([[4, 3, 6, 3, 9],
       [7, 3, 6, 9, 4],
       [3, 6, 3, 8, 3],
       [4, 8, 7, 7, 4],
       [4, 3, 7, 2, 7]])

In [23]:
matrix[2:4,1:4] #slicing to obtain a certain set of rows and columns

array([[6, 3, 8],
       [8, 7, 7]])

In [24]:
matrix[3][4] #extracting an element from the matrix

4